# Generated by Django 5.2.5 on 2025-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(unique=True)),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('is_user_migrated', models.BooleanField(default=False)),
            ],
        ),
    ]
