# Generated by Django 5.2.5 on 2025-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(unique=True)),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
