# Generated by Django 5.2.5 on 2025-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(unique=True)),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('parent_origin_id', models.IntegerField(blank=True, null=True)),
                ('parent_destination_id', models.IntegerField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
