# Generated by Django 5.2.5 on 2025-09-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('parent_cloud_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT_ID на облаке')),
                ('parent_box_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT_ID на коробке')),
                ('real_obj_cloud_id', models.IntegerField(blank=True, null=True, verbose_name='REAL_OBJ_ID на облаке')),
                ('real_obj_box_id', models.IntegerField(blank=True, null=True, verbose_name='REAL_OBJ_ID на коробке')),
                ('parent_real_obj_cloud_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT REAL_OBJ_ID на облаке')),
                ('parent_real_obj_box_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT REAL_OBJ_ID на облаке')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('folders_in_cloud', models.IntegerField(blank=True, null=True, verbose_name='Папок на облаке')),
                ('folders_in_box', models.IntegerField(blank=True, null=True, verbose_name='Папок на коробке')),
                ('files_in_cloud', models.IntegerField(blank=True, null=True, verbose_name='Файлов на облаке')),
                ('files_in_box', models.IntegerField(blank=True, null=True, verbose_name='Файлов на коробке')),
                ('is_sync', models.BooleanField(default=False, verbose_name='Синхронизировано')),
            ],
        ),
    ]
