# Generated by Django 5.2.5 on 2025-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0004_folder_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('parent_cloud_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT_ID на облаке')),
                ('parent_box_id', models.IntegerField(blank=True, null=True, verbose_name='PARENT_ID на коробке')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
    ]
