# Generated by Django 5.2.5 on 2025-09-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0004_folder_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='files_in_box',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Файлов на коробке'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='files_in_cloud',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Файлов на облаке'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='folders_in_box',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Папок на коробке'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='folders_in_cloud',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Папок на облаке'),
        ),
    ]
