# Generated by Django 5.2.5 on 2025-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0004_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.IntegerField(unique=True)),
                ('destination_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
