# Generated by Django 5.2.5 on 2025-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0005_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер в битах'),
        ),
    ]
