# Generated by Django 5.2.5 on 2025-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0005_alter_storage_files_in_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='is_sync',
        ),
        migrations.AddField(
            model_name='storage',
            name='files_sync',
            field=models.BooleanField(default=False, verbose_name='Файлы синхронизированы'),
        ),
        migrations.AddField(
            model_name='storage',
            name='folders_sync',
            field=models.BooleanField(default=False, verbose_name='Папки синхронизированы'),
        ),
    ]
