# Generated by Django 5.2.5 on 2025-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0006_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('dest', models.CharField(blank=True, null=True, verbose_name='Назначение')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Запись синхронизирована')),
            ],
        ),
    ]
