# Generated by Django 5.2.5 on 2025-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0006_remove_storage_is_sync_storage_files_sync_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_real_obj_box_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_real_obj_cloud_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='real_obj_box_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='real_obj_cloud_id',
        ),
        migrations.AddField(
            model_name='storage',
            name='entity_type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип хранилища'),
        ),
    ]
