# Generated by Django 5.2.5 on 2025-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0007_logmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='blogposts_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
