# Generated by Django 5.2.5 on 2025-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0008_group_blogposts_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('group_is_sync', models.BooleanField(default=False, verbose_name='Группа синхронизована')),
                ('cloud_parent_id', models.IntegerField(blank=True, null=True, verbose_name='ID родительской задачи на коробке')),
                ('box_parent_id', models.IntegerField(blank=True, null=True, verbose_name='ID родительской задачи на коробке')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Запись синхронизирована')),
            ],
        ),
    ]
