# Generated by Django 5.2.5 on 2025-10-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0009_taskmigration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
