# Generated by Django 5.2.5 on 2025-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmigration',
            name='cloud_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID группы на облаке'),
        ),
    ]
