# Generated by Django 5.2.5 on 2025-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0012_taskmigration_cloud_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmigration',
            name='cloud_group_id',
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='box_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID группы на коробке'),
        ),
    ]
