# Generated by Django 5.2.5 on 2025-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0013_remove_taskmigration_cloud_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stageMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('cloud_group_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы на облаке')),
                ('box_group_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы на коробке')),
            ],
        ),
    ]
