# Generated by Django 5.2.5 on 2025-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0014_stagemigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemigration',
            name='cloud_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID на облаке'),
        ),
    ]
