# Generated by Django 5.2.5 on 2025-10-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0015_alter_stagemigration_cloud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemigration',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='Стадия синхронизирована'),
        ),
    ]
