# Generated by Django 5.2.5 on 2025-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0016_stagemigration_is_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemigration',
            name='cloud_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID на облаке'),
            preserve_default=False,
        ),
    ]
