# Generated by Django 5.2.5 on 2025-10-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0017_alter_stagemigration_cloud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmigration',
            name='with_files',
            field=models.BooleanField(default=False, verbose_name='Есть прикреплённые файлы'),
        ),
    ]
