# Generated by Django 5.2.5 on 2025-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0018_taskmigration_with_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('cloud_task_id', models.IntegerField(blank=True, null=True, verbose_name='ID задачи на облаке')),
                ('box_task_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы на коробке')),
                ('with_files', models.BooleanField(default=False, verbose_name='Есть прикреплённые файлы')),
            ],
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='comm_box_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во комментариев (коробка)'),
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='comm_cloud_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во комментариев (облако)'),
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='comm_sync',
            field=models.BooleanField(default=False, verbose_name='Комментарии синхронизованы'),
        ),
    ]
