# Generated by Django 5.2.5 on 2025-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0019_commentmigration_taskmigration_comm_box_cnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmigration',
            name='with_files',
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='attached_files',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во прикрепленных файлов'),
        ),
        migrations.AddField(
            model_name='taskmigration',
            name='file_synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизация по файлам'),
        ),
    ]
