# Generated by Django 5.2.5 on 2025-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0020_remove_taskmigration_with_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('cloud_obj_id', models.IntegerField(blank=True, null=True, verbose_name='objectID на облаке')),
                ('box_obj_id', models.IntegerField(blank=True, null=True, verbose_name='objectID на коробке')),
                ('cloud_task_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы на облаке')),
                ('box_task_id', models.IntegerField(blank=True, null=True, verbose_name='ID группы коробке')),
            ],
        ),
    ]
