# Generated by Django 5.2.5 on 2025-10-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0021_taskattachedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmigration',
            name='desc_updated',
            field=models.BooleanField(default=False, verbose_name='Описание обновлено'),
        ),
    ]
