# Generated by Django 5.2.5 on 2025-11-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0022_taskmigration_desc_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmigration',
            name='checklist_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во чеклистов в задаче'),
        ),
    ]
