# Generated by Django 5.2.5 on 2025-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0023_taskmigration_checklist_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(unique=True, verbose_name='ID на облаке')),
                ('box_id', models.IntegerField(blank=True, null=True, verbose_name='ID на коробке')),
                ('parent_cloud_id', models.IntegerField(unique=True, verbose_name='родительское ID на облаке')),
                ('parent_box_id', models.IntegerField(blank=True, null=True, verbose_name='родительское ID на коробке')),
                ('with_files', models.BooleanField(default=False, verbose_name='Есть прикреплённые файлы')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано')),
            ],
        ),
    ]
