# Generated by Django 5.2.5 on 2025-11-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0024_checklistpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpoints',
            name='cloud_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID задачи на облаке'),
        ),
    ]
