# Generated by Django 5.2.5 on 2025-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0025_checklistpoints_cloud_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistpoints',
            name='parent_cloud_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='родительское ID на облаке'),
        ),
    ]
