# Generated by Django 5.2.5 on 2025-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inarctica_migration', '0026_alter_checklistpoints_parent_cloud_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostsUpdating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_was', models.IntegerField(blank=True, null=True, verbose_name='ID которое было на коробке')),
                ('id_become', models.IntegerField(unique=True, verbose_name='ID которое стало на коробке')),
                ('cloud_id', models.IntegerField(blank=True, null=True, verbose_name='ID которое есть на облаке')),
            ],
        ),
    ]
